# Generated by Django 6.0.2 on 2026-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
